First version
lavsasha/Neural-Networks-from-Scratch pull request #1
Opened 2024-01-08 14:58 UTC by lavsasha

2024-01-08 19:40 UTC, DimaTrushin requested changes
Пара общих  замечаний.
1) Не хватает системы сборки и информации как собрать или подключить проект. Хорошо было бы добавить файлы с тестами, где бы демонстрировалась работа кода.
2) Я сделал замечания в отдельных местах. Если где-то встречалась похожая проблема, я не повторял замечание. Я рассчитываю, что ты по аналогии найдешь эти места и поправишь аналогично.
3) Самая большая проблема -- функция train ее надо переписать. В текущей версии это просто кошмар. Основная беда в том, что ты все время используешь разные типы данных для разных функций на вход. В итоге ты вместо полезной работы в алгоритмах только перекопируешь эти данные в другие контейнеры и передаешь дальше. Это плохо. Ты не должна перепаковывать данные. Данные должны лежать нетонутыми и они должны быть одним и единственным источником правды. Ты можешь на них ссылаться или адресовать или идти по ним с помощью итераторов, но НИКОГДА не копируй те данные, что у тебя есть. Это не только в методе train это по всему коду разбросано.
4) У тебя очень много где висят строчки вида
Eigen::MatrixXd M(a.size(), b.size());
M = x;
Это плохо. Первой строчки просто не должно быть. У тебя создается лишняя пустая матрица и потом аллоцированная под нее память удаляется. Ты делаешь кучу лишней работы с кучей.
Все матрицы в Eigen должны строиться одним выражением (желательно в одно выражение, я описал почему так в комментариях) и только с помощью матричных операций. Перепиши все в виде матричных операций.
5) Еще используй using-ги в начале каждого класса. Используй namespace. И закрой приватные данные во всех классах.
6) В целом код читать можно.

2024-01-08 19:40 UTC, DimaTrushin commented on .gitignore
Очень странно что этот файл пустой. Этот файл обычно нужен, чтобы не заливались лишние файлы в git. Ты руками это контролируешь? Или ты заливаешь не через консоль?

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.h
> +};
Кирпичи в конце файлов. Добавь новую пустую строку в конце каждого файла. На эту вещь исторически ругается гит. Все, кто будет клонить твой репозиторий будут видеть эти ошибки от гита. Так не хорошо делать.

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.h
> +
Не пиши в global namespace. Заведи имя для окружения и пиши все внутри него, например
```cpp
namespace NeuralNets {
// весь твой код
}
```

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.h
> +#include <Eigen/Dense>
Плохая тема. У тебя подключена библиотека, которой нет в репозитории. То есть пользователь твоей библиотеки не сможет ее собрать. Ему придется разбираться, как твоя библиотека устроена. Это плохо. Лучше подключить Eigen как git submodule. Прочитай вот тут https://git-scm.com/book/en/v2/Git-Tools-Submodules как это работает.

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.h
> +    static double FindDist(const Eigen::MatrixXd &z, const Eigen::MatrixXd &y);
Не используй сырые типы. Это как использование магических констант в коде. Вместо этого в начале каждого класса заведи using-ги в которых храни нужные типы. А именно
```cpp
using Matrix = Eigen::MatrixXd;
```
Это в частности избавит тебя от необходимости писать длинные паршивые типы.

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.h
> +    static std::pair<double, std::vector<Eigen::MatrixXd>> CalcPenalty(
Никогда не используй std::pair, потому что ты хрен поймешь какой смысл у полей first и second. Вместо этого заведи структуру, можно хоть внутри этого класса с говорящими полями, например
```cpp
struct PenaltyResult {
  using Matrix = Eigen::MatrixXd;
  using ТипОписывающийЧтоЭтоЗаХрень = std::vector<Matrix>;
  double ПеременнаяСГоворящимИменем;
  ТипОписывающийЧтоЭтоЗаХрень ПеременнаяСГоворящимИменем;
};
```
И из функции возвращать эту структуру. Потом вызывающий сможет обратиться к полям структуры по нормальным именам вместо first и second.

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.h
> +            const std::vector<std::pair<Eigen::MatrixXd, Eigen::MatrixXd>> &data, std::vector<Layer> &network);
- Есть несколько проблем
1) Длинные имена типов, за которыми теряется всякий смысл. Это сложно читать.
2) Мне не нравится сигнатура. Почему эта функция принемает слои нейросети? Она про это ничего не должна знать. Она лишь должна знать про выход из нейросети и правильный выход на данных.
3) Почему слои передаются по неконстантной ссылке? Этот метод мутирует сеть? Схрена ли? Об этом ничего в названии не сказано.

- Что это за метод? Он считает ошибку на всех данных? Тогда я бы ожидал такую сигнатуру для аргументов
(const Data& data, const Network& net);
А что он возвращает? Почему он возвращает что-то кроме double? Если он возвращает что-то еще, то это не просто calculatePenalty это что-то другое мы считаем. В общем не сходится название метода и сигнатура.
- Либо еще лучше, можно сделать
(const YContainer& y, const YContainer f_of_x)
где первый аргумент -- это только y данные из обучающей выборки. А второй аргумент -- это значение нейросети на нужных x. Тогда у тебя этот файл не будет зависеть от нейросети и можено убрать #include<Layer.h>

- И еще мое решение предлагает завести специальный тип для данных.

- И еще у тебя data -- это батч или все данные? Это не ясно из названия и метода.

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.h
> +    static Eigen::MatrixXd FindInitialRow(const std::vector<std::pair<Eigen::MatrixXd,
Я бы назвал метод findInitialGradient

2024-01-08 19:40 UTC, DimaTrushin commented on Sigma.h
> +    static Eigen::MatrixXd EvaluateFunc(const Eigen::MatrixXd &x);
Я правильно понимаю, что это уже для батча?

2024-01-08 19:40 UTC, DimaTrushin commented on Sigma.cpp
> +    for (int i = 0; i < x.rows(); ++i) {
У Eigen есть метод применить функцию ко всем элементам. Не надо писать такой цикл. Вот тут прочти https://stackoverflow.com/questions/33786662/apply-function-to-all-eigen-matrix-element

2024-01-08 19:40 UTC, DimaTrushin commented on Sigma.cpp
> +            res(i, j) = exp(x(i, j)) / pow(exp(x(i, j)) + 1, 2);
- Вот это плохо. У тебя будут проблемы с точностью. У тебя присутствует деление экспоненты на экспоненту, при положительных x(i, j) у тебя лопнет по точности double.
- Ты точно правильно производную вычислила? У тебя куда минус пропал из экспоненты? Кажется что тут надо минус добавить внутри экспоненты. На даже после этого лучше раскрыть скобки в знаменателе и все в знаменатель убрать.

2024-01-08 19:40 UTC, DimaTrushin commented on Layer.h
> +    Eigen::MatrixXd A;
- Не делай публичные данные. Данные специально делаются приватными, чтобы обеспечить инвариант.
- Сделай A_ или m_A вместо просто A. Причина в том, что локальные переменные являются "глобальными данными" для методов класса. Потому их надо уметь отличать от локальных переменных метода. Такое обозначение позволяет это сделать.

2024-01-08 19:40 UTC, DimaTrushin commented on Layer.h
> +    Eigen::MatrixXd b;
А почему не Eigen::VectorxXd?

2024-01-08 19:40 UTC, DimaTrushin commented on Layer.h
> +    Layer(int64_t m, int64_t n);
У тебя тут сырые типы int64_t. В Eigen индексы для элементов матрицы int. У тебя каша с типами. Заведи using вида
```cpp
using IndexType = int;
```
Или что-то в этом духе. В каждом классе в начале определи все типы, которые ему нужны для использования и потом используй только псевдонимы.

2024-01-08 19:40 UTC, DimaTrushin commented on Layer.cpp
> +    std::normal_distribution<double> distribution(0.0, 1.0);
Очень плохая идея так делать рандом. Лучше завести глобальный объект в виде синглтона и получать доступ к нему. Вообще есть EigenRand https://bab2min.github.io/eigenrand/v0.5.0/en/index.html это библиотека, которая позволяет тебе задать случайно матрицы из Eigen удобным способом. Подключи ее как git submodule.

2024-01-08 19:40 UTC, DimaTrushin commented on Layer.cpp
> +    b.resize(m, 1);
Это питонячий стиль. В идеале в плюсах все данные должны инициализироваться в списке инициализации, например я бы ожидал что-то такое
```cpp
Layer::Layer(IndexType rows, IndexType columns)
  : A_(Rand::getNormal(rows, columns)),
    b_(Rand::getNormal(rows, 1)) {}
```
где Rand -- это класс или глобальный объект отвечающий за рандом.

2024-01-08 19:40 UTC, DimaTrushin commented on Layer.cpp
> +Layer::Layer(int64_t m, int64_t n) {
Плохие названия переменных, не понятно что из них столбцы, что строки. Разным пользователям будет не очевидно. Потому что есть разные натации.

2024-01-08 19:40 UTC, DimaTrushin commented on Layer.h
> +    Eigen::MatrixXd CalcLayerValue(const Eigen::MatrixXd &x);
Слишком длинное название evaluate вполне сойдет.

2024-01-08 19:40 UTC, DimaTrushin commented on Layer.cpp
> +    }
1) Это называется нарушение уровня абстракции, если ты помнишь с лекции. У тебя тут идет более низкоуровневая работа по сравнению с тем, что идет дальше. Потому что ниже ты оперируешь на уровне матриц, а тут оперируешь на уровне элементов матриц. У тебя не хватает вспомогательной функции, которая делает эту работу.

2) Это делается сильно проще. Тебе надо иметь вспомогательный вектор v = (1, 1, ..., 1) размера 1 на cols(). и тогда все обойдется формулой
```cpp
Matrix result = A_ * x + b_ * v;
```
И чтобы не считать v руками можно завернуть его в метод под названием getRowOf1(int rows); И тогда будет
```cpp
Matrix result = A_ * x + b_ * getRowOf1(x.cols());
```
И в таком виде это можно завернуть в одну строчку.

2024-01-08 19:40 UTC, DimaTrushin commented on Layer.cpp
> +    Eigen::MatrixXd grad(A.rows(), A.cols());
По идее тебе нигде не надо создавать пустые матрицы нужного размера. Все матрицы должны строиться с помощью операций.

2024-01-08 19:40 UTC, DimaTrushin commented on Layer.cpp
> +    Eigen::MatrixXd x_tr = x.transpose();
Старайся не заводить промежуточных матриц, а пиши сразу финальные выражения. Дело в том, что Eigen умеет оптимизировать вычисления длинных сложных выражений во время компиляции, а если ты все положишь в отдельные матрицы и сама укажешь порядок действий, то Eigen не сможет ничего сделать.

2024-01-08 19:40 UTC, DimaTrushin commented on Layer.cpp
> +    }
Проблема что и выше в нарушении уровня абстракции.

2024-01-08 19:40 UTC, DimaTrushin commented on Layer.cpp
> +    }
Опять нарушение уровня абстракции. Если тебе надо сложить все столбцы матрицы, то это делается умножением на строку из 1.

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.cpp
> +    }
Ну есть же метод std::accumulate

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.cpp
> +    Eigen::MatrixXd x(data[0].first.rows(), data.size());
Когда тебе приходится писать код вида
```cpp
data[0].first.rows()
```
То это ошибка границ взаимодействия. Ты лезешь в объект, причем в контейнер, потом именно в его первый элемент (не второй, не третий, а первый), потом в first, а потом метод rows(). Это ошибка. Это значит, что ты передаешь слишком высокоуровневые данные, в которые тебе приходится залезать. То есть у data в интерфейсе не достаточно методов, чтобы взаимодействовать с кодом этой функции.

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.cpp
> +    }
Вот тут ты по сути зря копируешь свои данные из std::vector в Eigen::MatrixXd. Зачем? У тебя явно плохо проработан интерфейс. Данные с которыми ты работаешь в функции ей не подходят. Значит надо передавать только те данные, которые этой функции подходят.

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.cpp
> +    res /= static_cast<double>(data.size());
Тут можно не использовать static_cast, но хуже от него не будет.

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.cpp
> +    }
Низкоуровневая работа.

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.cpp
> +    return {res, z};
Функция делает что-то странное. Опиши мне словами, что ты тут хочешь сделать и для чего.

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.cpp
> +    Eigen::MatrixXd u(static_cast<int64_t>(data.size()), data[0].second.rows());
Касты говорят о том, что у тебя не правильно предусмотрены типы данных. Эта функция высокоуровневая, она не должна заниматься кастованием данных. Если ты хочешь преобразование к знаковому типу, и у тебя есть c++20, то ты можешь использовать ssize() у вектора. Но вообще говоря этой строчки вообще не должно быть.

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.cpp
> +    }
Ты не должна построчна работать с матрицами. Перепиши все в матричных операциях. Это касается не только этого места.

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.cpp
> +    Network net(network);
Какого хрена тут происходит? Зачем ты копируешь целиком нейросеть!? Это же потенциально дофига очень дорогих операций. И главное не понятно зачем тебе это надо.

2024-01-08 19:40 UTC, DimaTrushin commented on Penalty.cpp
> +    Eigen::MatrixXd z = net.CalcNetworkValue(x).back();
Опять обращение по точке дважды. Это опять нарушение уровня доступа.

2024-01-08 19:40 UTC, DimaTrushin commented on Network.h
> +    std::vector<Layer> layers;
Приватные данные.

2024-01-08 19:40 UTC, DimaTrushin commented on Network.h
> +    explicit Network(const std::vector<Layer>& net);
1) Плохо делать конструктор от деталей имплементации. Пользователь вообще не должен знать, как ты внутри хранишь слои. Я видел где это используется. Так быть не должно. Убери этот конструктор и никогда его не используй. Все места, что его используют надо убрать и переписать. Все эти места -- ошибка проектирования.
2) Иногда бывает что такие конструкторы нужны, но тогда их лучше делать от rvalue ссылки, то есть std::vector<Layer>&&, чтобы потом сделать Layers_(std::move(Layers)). Иначе это очень, очень, очень дорогая операция.

2024-01-08 19:40 UTC, DimaTrushin commented on Network.h
> +    Network(size_t num_of_layers, const std::vector<std::pair<int64_t, int64_t>>& params);
1) У тебя куча разных сырых типов.
2) Не используй конкретные контейнеры для передачи аргументов. Во-первых, это привяжет тебя к использованию этих контейнеров. Во-вторых, это потенциально черевато созданием тяжелых временных объектов и лишних копий. Тут у тебя параметры легкие, то лучше использовать std::initializer_list<Size>, где Size -- это структура задающая размер матрицы. То есть
```cpp
struct Size {
  using Index = Eigen::Index;
  Index rows;
  Index columns;
};
```
3) Пока я это писал я понял, что это тоже плохо. Потому что тогда тебе надо указывать одинаковые размеры дважды, а именно, если тебе нужна сеть с размерами слоев 3, 4, 5, то тебе придется указывать {{4, 3}, {5, 4}}. То есть параметр 4 должен быть согласован. Кроме того, у тебя еще и num_of_layers лишний. Потому что он просто равен params.size().
4) Вместо всего этого балагана я бы ожидал следующее
```cpp
Network(std::initializer_list<Index> layer_dim);

Network net({3, 4, 5});
```
И у тебя создается сеть со слоями нужных размеров. 
Более того, в дальнейшем можно будет добавить std::initializer_list<FuncionID> где FunctionID будут указывать разные пороговые функции для слоев.

2024-01-08 19:40 UTC, DimaTrushin commented on Network.h
> +    std::vector<Eigen::MatrixXd> CalcNetworkValue(const Eigen::MatrixXd &x);
1) Название длинное. 
2) Почему возвращает вектор из матриц? Это что-то странное.

2024-01-08 19:40 UTC, DimaTrushin commented on Network.h
> +                      double eps, size_t max_step, int coef);
1) сырые типы
2) Что такое coef??? И почему он int а не double если это шаг? И почему название такое странное?
3) Не делай batch_size беззнаковым. Вообще старайся не работать с беззнаковыми типами. Они нужны только если тебе нужны всякие битовые маски.

2024-01-08 19:40 UTC, DimaTrushin commented on Network.cpp
> +        layers.push_back(new_layer);
1) В начале надо бы сделать layers_.reserve(params.size());
2) У тебя лишнее копирование слоя, потому чтобы его избежать надо писать
```cpp
layers_.push_back(std::move(new_layer));
```
3) Но еще лучше вообще избежать построения временного объекта и сделать так
```cpp
layers_.emplace_back(first, second);
```
И еще если тебе нужен loop, то в данном случае лучше range loop вида
```cpp
for (auto p : params) 
  layers_.emplace_back(p.first, p.second);
```
4) Но тут вообще надо все писать по-другому. Я в h файле написал подробно что и как надо поменять. Тем не менее, решил прокомментировать что тут было не так.

2024-01-08 19:40 UTC, DimaTrushin commented on Network.cpp
> +    Eigen::MatrixXd temp(x.rows(), x.cols());
Это лишнее создание пустой матрицы. По сути ты тут аллоцируешь память. Потом ниже в строчке 17 ты переприсваиваешь temp = x. И в итоге ты забываешь аллоцированную память и делаешь новую копию x. Зачем это сделано не понятно.

2024-01-08 19:40 UTC, DimaTrushin commented on Network.cpp
> +        val.push_back(temp);
1) Плохо переиспользовать эту переменную в цикле. Ты по сути хочешь сделать так
```cpp
val.push_back(x);
for (const auto& layer : layers_)
  val.push_back(layer.evaluate(val.back()));
```
Тут правда будет лишний x храниться в начале. Надо как-то это поменять.

2) Что реально тут плохо -- не хватает val.push_back(std::move(temp));

3) Ну и конечно сокращенные названия val и l никуда не годятся.

2024-01-08 19:40 UTC, DimaTrushin commented on Network.cpp
> +    while (true) {
Нет ничего лушче, чем while(true). Никогда так не пиши. Это значит, что ты понятия не имеешь, когда остановится твой цикл. А это значит, что у тебя просто нет гарантии остановки. И это потенциально значит, что он никогда не закончится. Это плохой стиль, это ошибка дизайна. Это надо переделать.

2024-01-08 19:40 UTC, DimaTrushin commented on Network.cpp
> +            for (int i = static_cast<int>(layers.size() - 1); i >= 0; --i) {
Вот тут у тебя три вложенных цикла. Ты можешь гарантировать корректность работы такой программы? Я не уверен, что ты даже понимаешь, какой у тебя тут инвариант у каждого цикла выполняется.

Когда у тебя куча вложенных циклов, это значит, что у тебя одна функция в цикле вызывает другую функцию, которую ты не обозначила.

2024-01-08 19:40 UTC, DimaTrushin commented on Network.cpp
> +        if ((step + 1) * batch_size <= num_of_batches * batch_size) {
Вот что это за условие? Как его вообще читать. Что тут проверяется?

2024-01-08 19:40 UTC, DimaTrushin commented on Network.cpp
> +            batch.insert(batch.end(), data.begin() + static_cast<int64_t>(step * batch_size),
1) Опять касты. Убрать.
2) Кроме того, ты делаешь кучу лишних копирований данных из одних контейнеров в другие. Не создавай никаких промежуточних контейнеров. Если ты хочешь идти по батчу, задавай его парой итераторов -- начало и конец батча в контейнере и все. И передавай эти итераторы всюду.

2024-01-08 19:40 UTC, DimaTrushin commented on Network.cpp
> +void Network::Train(const std::vector<std::pair<Eigen::MatrixXd, Eigen::MatrixXd>> &data, size_t batch_size,
Тело этой функции надо переписать нормально на человеческом языке.

2024-03-25 16:51 UTC, lavsasha commented on Layer.cpp
> +    }
Так я тут не столбцы, а матрицы складываю. И я не понимаю, как создать матрицу grad сразу с помощью матричных операций, не создавая в начале пустую матрицу. Даже если сделать матрицу матриц, а потом умножить на столбец единиц (чтобы сложить эти матрицы), мне всё равно для этого нужно изначально создать пустую матрицу матриц, затем её заполнить, проходясь циклом, а только потом уже умножать на столбец единиц. Поэтому без понятия, как адекватно исправить это замечание(

2024-05-11 17:03 UTC, closed without merging